### ISSUE TITLE
源码里面插件开启后出错，关闭后没问题，没细看是那个插件影响

### ISSUE THREAD

**Issue by lchjczw** [yidashi/yii2cmf#13]
演示版好像有些功能没有同步到源码吗？比如插件

**Comment by yidashi** [comment]
源码里有插件啊

**Comment by lchjczw** [comment]
我给你列举一下，我安装后发现和演示不一样的地方哈
1、插件没有演示里面的多
2、源码的控制面板，连续点击两次就会在子窗口中重新打开一个控制面板
3、插件全部开启后，前台首页访问错误
4、演示里面有三个主题，源码里面后台才有一个主题
5、配置里面，自定义配置，中有系统配置和微信配置，还有一个重复的邮箱配置

**Comment by yidashi** [comment]
有的是bug，明天更新。

**Comment by lchjczw** [comment]
恩，辛苦了，只能帮你测出来，尽一点绵薄之力，希望越来越完善，越来越好用
