### ISSUE TITLE
如果把咱们这个系统迁移到postgresql这个数据库，不知道兼容不？

### ISSUE THREAD

**Issue by lchjczw** [yidashi/yii2cmf#14]
如果把咱们这个系统迁移到postgresql这个数据库，不知道兼容不？

**Comment by yidashi** [comment]
数据库迁移过去，程序肯定没问题。

**Comment by lchjczw** [comment]
那如果在安装的时候有选择安装数据库的类型，就可以直接安装成postgresql了，甚至可以新增其他的数据库支持，这样就更通用了

**Comment by lchjczw** [comment]
我已经把mysql数据库转换为pgsql了，大部分没问题，还是有些地方有问题

**Comment by yidashi** [comment]
这数据库没玩过 = =大概什么错误呢

**Comment by lchjczw** [comment]
有好几个地方那个，主要都是数据库sql语句的问题，存在不兼容的现象，因为mysql的语句有些不是标准的sql语句，比如说创建文章的时候：
common--》models->Category.php里面：130行
$query->where(new Expression("FIND_IN_SET('{$module}', module) "));
这个sql语句，里面的函数FIND_IN_SET，再postgres里面没有，所以会出错。

主要postgres数据库的功能挺强，事物，地理位置，空间类型，还有强大的json类型，基本上你需要的类型里面都可以直接提供

要不然我把数据库发你，你试试看

链接: https://pan.baidu.com/s/1gfsWc99 密码: 98h6
