### ISSUE TITLE
create_config_table  时报1064 42000  错误

### ISSUE THREAD

**Issue by rainforyou** [yidashi/yii2cmf#16]
我把insert语句全部删除后，才能顺利安装，之后手动导入到数据库。我查了下说有保留字段什么的，不知道是不是因为有个group字段的关系

**Comment by yidashi** [comment]
具体错误呢

**Comment by yidashi** [comment]
改mysql模式成非严格模式试试

**Comment by rainforyou** [comment]
http://dhnews.zjol.com.cn/pic/0/18/07/99/18079995_890072.jpg   错误截图

**Comment by yidashi** [comment]
我把migrate更新了一下，你再试一下，谢谢。

**Comment by rainforyou** [comment]
z支持这么好的系统··
