### ISSUE TITLE
上传头像保存时提示文件名为空，在测试站上传头像正常

### ISSUE THREAD

**Issue by rainforyou** [yidashi/yii2cmf#17]
exception 'yii\base\ErrorException' with message 'file_get_contents(): Filename cannot be empty' in /web/common/modules/attachment/models/Attachment.php:233
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'file_get_conten...', '/web/common/mod...', 233, Array)
#1 /web/common/modules/attachment/models/Attachment.php(233): file_get_contents('')
#2 /web/common/modules/user/controllers/SettingsController.php(63): common\modules\attachment\models\Attachment->makeCropStorage('200', '200', '136', '60')
#3 [internal function]: common\modules\user\controllers\SettingsController->actionAvatar()
#4 /web/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#5 /web/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#6 /web/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('avatar', Array)
#7 /web/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('user/settings/a...', Array)
#8 /web/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#9 /web/web/index.php(22): yii\base\Application->run()
#10 {main}

**Comment by yidashi** [comment]
attachment模块更新了下，你再试试。。

**Comment by rainforyou** [comment]
Exception 'Imagine\Exception\InvalidArgumentException' with message 'File /avatar/5b396d8e5301cbb76e343b03fd5a91fb.jpg does not exist.' 

in /web/vendor/imagine/imagine/lib/Imagine/Image/AbstractImagine.php:72

应该 是路劲有问题

**Comment by yidashi** [comment]
更新过了啊

**Comment by rainforyou** [comment]
可以了。棒棒的
刚刚我测试备份数据库，好像需要全选，备份，再翻页去一页页操作

**Comment by yidashi** [comment]
嗯。这个应该不分页，
