### ISSUE TITLE
缓存切换为redis 报错。只能用文件缓存吗？

### ISSUE THREAD

**Issue by chenhui1221** [yidashi/yii2cmf#23]
Redis error: ERR invalid expire time in set
Redis command was: SET bc3677d4d5f16cab739649cdb8e3ed74 a:2:{i:0;a:41:{i:0;s:2:"15";i:1;s:2:"16";i:2;s:2:"17";i:3;s:2:"22";i:4;s:2:"25";i:5;s:2:"26";i:6;s:2:"27";i:7;s:2:"29";i:8;s:2:"31";i:9;s:2:"32";i:10;s:2:"34";i:11;s:2:"37";i:12;s:2:"40";i:13;s:2:"41";i:14;s:2:"42";i:15;s:2:"43";i:16;s:2:"45";i:17;s:2:"53";i:18;s:2:"57";i:19;s:2:"58";i:20;s:2:"66";i:21;s:2:"67";i:22;s:2:"68";i:23;s:2:"69";i:24;s:2:"70";i:25;s:2:"72";i:26;s:2:"73";i:27;s:2:"75";i:28;s:2:"76";i:29;s:2:"77";i:30;s:2:"78";i:31;s:2:"79";i:32;s:2:"80";i:33;s:2:"82";i:34;s:2:"33";i:35;s:2:"39";i:36;s:2:"71";i:37;s:2:"30";i:38;s:2:"24";i:39;s:2:"44";i:40;s:2:"81";}i:1;O:25:"yii\caching\TagDependency":3:{s:4:"tags";s:14:"mdm.admin.menu";s:4:"data";a:1:{s:32:"3878ebf0ff4c3750dfa7098d752daa6c";s:21:"0.88899900 1489507577";}s:8:"reusable";b:0;}} PX -1702967296

**Comment by yidashi** [comment]
可以用的。哪里报的错？

**Comment by chenhui1221** [comment]
`就我把代码缓存那里切换为redis后，  'cache' => [
            'class' => 'yii\redis\Cache',
            'redis' => 'redis',
        ],。`  然后 过一会， 进任何页面都是这个提示了。

**Comment by yidashi** [comment]
你环境的问题。

**Comment by yidashi** [comment]
先把`backend/modules/rbac/components/Configs.php` 52行那个数改成0试试看

**Comment by chenhui1221** [comment]
改成0 是可以的。

**Comment by yidashi** [comment]
他最后应该是设置2592000*1000的，为什么到你那变成了一个负数-1702967296

**Comment by yidashi** [comment]
找到原因了吗~~

**Comment by mzq1210** [comment]
安装：输入管理员信息一步不走了，一直在loading是什么情况 谢谢

**Comment by yidashi** [comment]
不存在一直loading吧，建表建数据呢，就算失败也会有提示的。再开一个

**Comment by mzq1210** [comment]
还是安装不上去 ，输入管理员信息点击下一步的时候一直是loading，没有提示信息

**Comment by yidashi** [comment]
刚试了一下没重现你说的问题。你自己排查一下吧。看看开发者工具，到这一步那个异步请求返回什么了。

**Comment by mzq1210** [comment]
好的 谢谢

**Comment by chenhui1221** [comment]
2592000 * 1000        $expire = (int) ($expire * 1000);  redis/cache  这里有乘以1000，导致数字过大，int后就负数了。    很抱歉 ， 现在才看到  issue
