### ISSUE TITLE
系统菜单中的gii和迁移如果没安装建议不显示

### ISSUE THREAD

**Issue by rainforyou** [yidashi/yii2cmf#24]
安装后才在菜单显示这样相对友好

**Comment by phpyii** [comment]
还有个小问题就是框架外边有个debug调试栏iframe里也有一个debug调试栏 有什么好的解决方案

**Comment by yidashi** [comment]
`
public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            if ($action->id == 'index') {
                Yii::$app->getView()->off(View::EVENT_END_BODY, [Yii::$app->getModule('debug'), 'renderToolbar']);
                Yii::$app->getResponse()->off(Response::EVENT_AFTER_PREPARE, [Yii::$app->getModule('debug'), 'setDebugHeaders']);
            }
            return true;
        }
        return false;
    }
`

最近懒得更新代码了，你在SiteController里加个这就可以了。
