### ISSUE TITLE
点击首页分类按钮  更多>>> 报错

### ISSUE THREAD

**Issue by coolzog** [yidashi/yii2cmf#29]
打开首页分类的 更多>>> 按钮报错
报错内容  Class 'frontend\Widgets\area\TextWidget' not found    怎么解决....

**Comment by yidashi** [comment]
嗯，是个bug,把你 area_block 表里的widgets字段`frontend\Widgets\area`都改成`common\modules\area\widgets`

**Comment by coolzog** [comment]
好了  非常感谢！！
