### ISSUE TITLE
文件系统切换问题，同时感谢这个框架的作者们

### ISSUE THREAD

**Issue by LuXiZhong** [yidashi/yii2cmf#30]
由本地文件切换到云存储（七牛云）时，如果mysql数据库里有本地上传记录时，切换后，七牛云上传不报错，返回正常，但是图片没有保存成功，把mysql数据库里的记录删掉就好了

不知道是什么问题。。。。。

**Comment by yidashi** [comment]
因为同一个文件库里有记录会直接返回库里的图片。没考虑切换存储驱动，有不合理之处
