### ISSUE TITLE
打开前台就报错

### ISSUE THREAD

**Issue by bubifengyun** [yidashi/yii2cmf#32]
安装好，进入 http://localhost/ 

```
Unknow column 'view in 'order clause'
The SQL being executed was : SELECT * from `blog_book` ORDER BY `view` DESC LIMIT5
```

查看源码，发现数据库中 `book` 确实无 `view` 选项，见 *./database/migrations* 内。而 *./frontend/themes/basic/site/index.php* 中 `Book::find()->orderyBy('view desc')->limit(5)->all()` ，确实有问题。不知何解？谢谢。

**Comment by bubifengyun** [comment]
看意思，热门课程确实应该加上一个阅读量的排名，应该给 `book` 加上一个变量 `view`。就是修改 *./database/migrations* 下的内容更合适。

**Comment by yidashi** [comment]
嗯。少个view字段
