### ISSUE TITLE
建议修改前台页面布局

### ISSUE THREAD

**Issue by bubifengyun** [yidashi/yii2cmf#35]
可否考虑修改前台的上面菜单，一般网站都是只有上面一条，基本信息都显示在那边了。比如
+ http://www.oschina.net/
+ https://github.com/yidashi/yii2cmf

搜索，用户登录，网站名称等，都放在一行了，感觉很简洁。现在的网站布局，显得“头大”布局不是很美观。后台 AdminLTE 的那种布局也是不错的。可否考虑？

另外。这段时间要借鉴该模板，并以此开发新网站，不知道本网站的许可证是怎么发布的，会不会侵权。

如果设想好了新的前台布局，再来推送。谢谢。

**Comment by yidashi** [comment]
前台只是demo。随便用，随便改。

**Comment by bubifengyun** [comment]
谢谢。
