### ISSUE TITLE
非常遗憾，好多文件丢失

### ISSUE THREAD

**Issue by bubifengyun** [yidashi/yii2cmf#38]
对此当前和前段时间下载的版本，当前版本丢失了好几个文件。在实际操作中，一些操作都是找不到的。不知道什么原因导致的越更新文件丢失越严重。发生啥大事了吗。

**Comment by bubifengyun** [comment]
原来还可以用，现在变得越来越不好用了，还需要自己把内容从前面的版本更新过来

**Comment by yidashi** [comment]
...具体少了哪些文件，导致哪些操作404了，能说下么

**Comment by bubifengyun** [comment]
比如你刚刚修改的theme 。这个功能应该还是保留的吧。

在后台，原来存在这个theme 相关的controller 以及 view ，但是在2.0.1版本则没有了。打开为找不到网页。

前台一般添加的 view 都是theme文件夹，但是相关 theme 配置 view 路径的几个文件丢失了。比如 frontend/behavior，等。

不好意思，在手机上编辑，可能说的不是很清楚，上班时间没办法用电脑，等休息了，再折腾汇报。谢谢理解啊。

**Comment by yidashi** [comment]
主题是因为挪到模块里了，菜单忘了改,theme/default/index就可以了。抱歉抱歉，你先忙吧，有空了再折腾

**Comment by bubifengyun** [comment]
谢谢啦，顺便问一下，能否把投稿功能在公布出来。我折腾了半天，可能是因为URL 或者 view 路径设置的问题，一直没有折腾成功。后面添加其他动作controller，view 的放置一直是个问题，调整不好，跟自带的view 文件夹不在一起了。再次感谢😊

**Comment by bubifengyun** [comment]
非常感谢，这些问题都解决啦。没有注意模块这玩意，和composer铸成大错。改了一下午，今天终于明白。
