### ISSUE TITLE
前台，跟好友发私信的链接也是错的

### ISSUE THREAD

**Issue by bubifengyun** [yidashi/yii2cmf#39]
我先找找，看看能不能自行解决，再来完善。

**Comment by bubifengyun** [comment]
前台用户头像上传也失败了。

**Comment by bubifengyun** [comment]
评论文章，跳到评论成功的一个字符界面。应该跳转到文章所在界面吧。

**Comment by bubifengyun** [comment]
现在问题，还剩下两个。第一是给关注人发私信还会报错，说是notify link是常量，改动不得，第二，非管理员用户给管理员文章留言，会弹出邮箱不合RFC某格式的问题。我的是局域网，没有架设邮件服务器。邮箱绝对是正确的格式。不知道哪里出问题了。

**Comment by bubifengyun** [comment]
我正在看【Address in mailbox given does not comply with RFC 2822, 3.6.2. · Issue #382 · swiftmailer/swiftmailer】，分享给你，一起看吧！ https://github.com/swiftmailer/swiftmailer/issues/382

必应了一下，没能解决。等有时间再弄。

**Comment by bubifengyun** [comment]
现在更新到最新的版本，在点击关注别人的时候，仍旧会跳出异常。如图。
![_ _20170722153358](https://user-images.githubusercontent.com/4437214/28489309-ca9d4cdc-6ef3-11e7-81b7-dc235cf229c4.png)

发布文章的功能也存在部分问题。上传图片，不管评论还是投稿，都是无法成功的。

**Comment by bubifengyun** [comment]
发布文章上传图片产生的问题是 random_bytes 不存在。见图。
![_ _20170722154143](https://user-images.githubusercontent.com/4437214/28489407-10b42040-6ef6-11e7-9b15-4a894fd4b9b8.png)

找了一下，是 PHP 7 中才有的函数，对于 PHP 5.x 是没有该函数的。是不是要改一改 *composer.json* 的要求了。

**Comment by bubifengyun** [comment]
非管理员还是无法评论管理员的文章。
![_ _20170722162200](https://user-images.githubusercontent.com/4437214/28489646-f5e7607a-6ef9-11e7-9c84-650f11fb1555.png)

**Comment by yidashi** [comment]
发邮件应该没问题啊。

**Comment by bubifengyun** [comment]
我的仍旧没解决，等我把你的代码更新一下，再看看吧。非常感谢你的及时更新。我还在闷头改message的aftersave,准备加notify呢。现在在火车上，等回去改

**Comment by bubifengyun** [comment]
非常感谢这些问题都解决啦。

**Comment by bubifengyun** [comment]
再次发现，非管理员还是无法评论管理员的文章。依旧是邮件的问题。

**Comment by bubifengyun** [comment]
经过今天的调试，发现是安装的时候没有配置好导致的。在根目录下把.env文件中邮箱姓名和邮箱密码改成正常的邮箱及密码，就可以了。但是在安装的时候，不会提示去输入这个邮箱名字。
