### ISSUE TITLE
请教 composer.lock 可否删除

### ISSUE THREAD

**Issue by bubifengyun** [yidashi/yii2cmf#40]
不太清楚 composer.lock 功能如何。我的方式，下载，手动更改 *./composer.json*，因为之前做的网页有很多插件，想一次性全拖过来。 `composer install` 后，发现总是不会安装手动添加的，于是每次都把 *./composer.lock*删除就好了。

这个纯粹是出于好奇，没啥实际意义， *./composer.lock* 有没有存在的必要？谢谢。

**Comment by yidashi** [comment]
composer update 

可以删了，还是会生成出来的
