### ISSUE TITLE
存储位置不对

### ISSUE THREAD

**Issue by bubifengyun** [yidashi/yii2cmf#42]
上传图片错误，使用 firebug 查找问题，发现保存的链接位置不对。排除了一下问题。

+ 文件夹没有访问权限？有访问权限。
+ 没有上传成功？上传成功。
+ 文件名字也是对的，也可以读。

问题如下，正常存储，网站的网址是 http://localhost/www/yii2cmf-master/web/index.php?r=user%2Fsettings%2Favatar ，没有修改网址。但是图片的网址是 http://localhost/storage/upload/20170722/Jjjq3dSrHE94hFy388MKYoDqJ2cI0ro1YAlLFicN.jpg
发现没有弄对地址。是引用的时候地址不对。我在找，但是没有找到问题。

**Comment by yidashi** [comment]
这个应该是你安装的时候site_url没写对，.env里改下网站地址

**Comment by bubifengyun** [comment]
我是默认的，一路确定下来。看来是需要改一改了。
